# Generated by Django 2.2.13 on 2020-08-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shouji',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30)),
                ('n_star', models.IntegerField()),
                ('estimate', models.CharField(max_length=200)),
                ('sentiment', models.DecimalField(decimal_places=10, max_digits=11)),
            ],
        ),
    ]
